sudo: required

language: python

services:
  - docker
  - mysql

install:
  - docker pull mysql:5.7.14
  - mkdir db
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD=‘$3cureUS’ -v `pwd`/db:/var/lib/mysql mysql:5.7.14
  - sleep 10
  # MYSQL run in single line found here: http://stackoverflow.com/questions/1602904/how-do-you-run-a-single-query-through-mysql-from-the-command-line
  - docker ps -a
  - docker logs mysql
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 mysql -uroot -p’$3cureUS’ -h db -e “flush privileges; create user ‘www’@‘%’ identified by ‘\$3cureUS’;create database cs4501 character set utf8;grant all on cs4501.* to ‘www’@‘%’;grant all on test_cs4501.* to ‘www’@‘%’“;

script:
- docker-compose up
- docker exec -it cs4501_models_1 bash -c "./manage.py test"
