sudo: required

language: python

services:
  - docker

before_install:
- docker-compose down
- docker start mysql
- docker-compose up

script:
- docker exec -it cs4501_models_1 bash
- ./manage.py test
