# commands for docker. From https://docs.travis-ci.com/user/docker/
services:
  - docker

# commands for python. From https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.5"

# command to install dependencies

install: # prepare mySQL database
  - docker pull mysql:5.7.14
  - mkdir db
  - >
    docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS'
    -v `pwd`/db:/var/lib/mysql  mysql:5.7.14
#    wait for the bd container to start
  - sleep 15
  - >
    docker run -it --name mysql-cmd --rm --link mysql:db mysql:5.7.14
    mysql -uroot -p'$3cureUS' -h db -v -e
    "CREATE DATABASE cs4501 CHARACTER SET utf8;
    CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS';
    GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"

script:
- docker-compose up -d
- docker exec -it cs4501_models_1 bash -c "./manage.py test"
