sudo: required

language: python

services:
  - docker
  - mysql

before_install:
- docker-compose down
- docker pull mysql:5.7.14
- mkdir -p ~/cs4501/app
- mkdir ~/cs4501/db
- docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
- sleep 10
- docker run -i --name mysql-cmdline --link mysql:db mysql:5.7.14 bash -c "mysql -uroot -p'\$3cureUS' -h db" <<< "create user 'www'@'%' identified by '\$3cureUS';create database cs4501 character set utf8;grant all on cs4501.* to 'www'@'%';"

script:
- docker-compose up
- docker exec -it cs4501_models_1 bash -c "./manage.py test"
