models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./app:/app
    ports:
      - "8001:8000"
    command: bash -c "python /app/leaseMe/manage.py makemigrations marketplace && python /app/leaseMe/manage.py migrate marketplace && python /app/leaseMe/manage.py loaddata /app/leaseMe/db.json && mod_wsgi-express start-server --working-directory /app/leaseMe --reload-on-changes /app/leaseMe/leaseMe/wsgi.py"
