models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./app/leaseMe:/app
    command: bash -c "python /app/manage.py makemigrations marketplace && python /app/manage.py migrate marketplace && python /app/manage.py loaddata /app/db.json && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/leaseMe/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   volumes:
      - ./app/exp:/app
   command: "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/exp/wsgi.py"

web1:
   image: tp33/django
   links:
      - exp:exp-api
   volumes:
      - ./app/web:/app
   command: "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/web/wsgi.py"   

web2:
   image: tp33/django
   links:
      - exp:exp-api
   volumes:
      - ./app/web:/app
   command: "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
      - ./app/batch:/app
   links:
      - kafka:kafka
      - es:es
   command: "python /app/script.py"

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web1:web1
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web1:web1
  volumes:
    - ./app/selenium:/app
  command: bash -c "pip install selenium==3.7.0 && python seleniumTest.py"

haproxy:
   build: ./app/haproxy
   container_name: haproxy
   links:
      - web1:web1
      - web2:web2
   ports:
      - "8000:8000"
